sequenceDiagram
    actor User
    participant BalanceController
    participant BalanceService
    participant CuentaNegocioService
    participant NegocioContableService
    participant CuentaMovimientoUnificadoService
    participant DB

    User->>+BalanceController: GET /processCuenta/{...}
    BalanceController->>+BalanceService: processCuenta(params)
    
    BalanceService->>+CuentaNegocioService: findAllByNumeroMaestro(numeroMaestro)
    CuentaNegocioService->>+DB: SELECT * FROM cuentanegocio WHERE ...
    DB-->>-CuentaNegocioService: List_CuentaNegocio
    CuentaNegocioService-->>-BalanceService: List_CuentaNegocio

    loop Para_cada_CuentaNegocio_en_paralelo
        BalanceService->>+NegocioContableService: totalesEntreFechasByNegocio(...)
        NegocioContableService-->>-BalanceService: Mono_Tuple2_BigDecimal_BigDecimal_totales
        
        alt TotalDebe_mayor_0
            BalanceService->>+CuentaMovimientoUnificadoService: findByUnique(...)
            CuentaMovimientoUnificadoService->>+DB: SELECT * FROM movconunif WHERE ...
            DB-->>-CuentaMovimientoUnificadoService: puede_no_encontrar
            CuentaMovimientoUnificadoService-->>-BalanceService: ID_o_null
            
            BalanceService->>+CuentaMovimientoUnificadoService: add_movimientoDebe
            CuentaMovimientoUnificadoService->>+DB: INSERT_UPDATE_movconunif
            DB-->>-CuentaMovimientoUnificadoService: OK
            CuentaMovimientoUnificadoService-->>-BalanceService: 
        end

        alt TotalHaber_mayor_0
            BalanceService->>+CuentaMovimientoUnificadoService: findByUnique(...)
            CuentaMovimientoUnificadoService->>+DB: SELECT * FROM movconunif WHERE ...
            DB-->>-CuentaMovimientoUnificadoService: puede_no_encontrar
            CuentaMovimientoUnificadoService-->>-BalanceService: ID_o_null

            BalanceService->>+CuentaMovimientoUnificadoService: add_movimientoHaber
            CuentaMovimientoUnificadoService->>+DB: INSERT_UPDATE_movconunif
            DB-->>-CuentaMovimientoUnificadoService: OK
            CuentaMovimientoUnificadoService-->>-BalanceService: 
        end
    end

    BalanceService-->>-BalanceController: Mono_List_String_errores
    BalanceController-->>-User: 200_OK_con_lista_de_errores
