sequenceDiagram
    actor User
    participant BalanceController
    participant BalanceService
    participant CuentaNegocioService
    participant NegocioContableService
    participant CuentaMovimientoUnificadoService
    participant DB

    User->>+BalanceController: GET /processCuenta/{...}
    BalanceController->>+BalanceService: processCuenta(params)
    
    BalanceService->>+CuentaNegocioService: findAllByNumeroMaestro(numeroMaestro)
    CuentaNegocioService->>+DB: SELECT * FROM cuentanegocio WHERE ...
    DB-->>-CuentaNegocioService: List<CuentaNegocio>
    CuentaNegocioService-->>-BalanceService: List<CuentaNegocio>

    loop Para cada CuentaNegocio (en paralelo)
        BalanceService->>+NegocioContableService: totalesEntreFechasByNegocio(...)
        NegocioContableService-->>-BalanceService: Mono<Tuple2<BigDecimal, BigDecimal>> (totales)
        
        alt TotalDebe > 0
            BalanceService->>+CuentaMovimientoUnificadoService: findByUnique(...)
            CuentaMovimientoUnificadoService->>+DB: SELECT * FROM movconunif WHERE ...
            DB-->>-CuentaMovimientoUnificadoService: (puede no encontrar)
            CuentaMovimientoUnificadoService-->>-BalanceService: (ID o null)
            
            BalanceService->>+CuentaMovimientoUnificadoService: add(movimientoDebe)
            CuentaMovimientoUnificadoService->>+DB: INSERT/UPDATE movconunif
            DB-->>-CuentaMovimientoUnificadoService: OK
            CuentaMovimientoUnificadoService-->>-BalanceService: 
        end

        alt TotalHaber > 0
            BalanceService->>+CuentaMovimientoUnificadoService: findByUnique(...)
            CuentaMovimientoUnificadoService->>+DB: SELECT * FROM movconunif WHERE ...
            DB-->>-CuentaMovimientoUnificadoService: (puede no encontrar)
            CuentaMovimientoUnificadoService-->>-BalanceService: (ID o null)

            BalanceService->>+CuentaMovimientoUnificadoService: add(movimientoHaber)
            CuentaMovimientoUnificadoService->>+DB: INSERT/UPDATE movconunif
            DB-->>-CuentaMovimientoUnificadoService: OK
            CuentaMovimientoUnificadoService-->>-BalanceService: 
        end
    end

    BalanceService-->>-BalanceController: Mono<List<String>> (errores)
    BalanceController-->>-User: 200 OK con lista de errores
